In [3]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ckcma\onedrive\desktop\tft_game_dataset\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df1 = pd.read_csv("TFT_Champion_CurrentVersion.csv")
df2 = pd.read_csv("TFT_Item_CurrentVersion.csv")
df3 = pd.read_csv("TFT_Challenger_MatchData.csv")
df4 = pd.read_csv("TFT_Diamond_MatchData.csv")
df5 = pd.read_csv("TFT_Master_MatchData.csv")
df6 = pd.read_csv("TFT_GrandMaster_MatchData.csv")
df7 = pd.read_csv("TFT_Platinum_MatchData.csv")

In [ ]:
# 데이터 정보 확인

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             52 non-null     object
 1   cost             52 non-null     int64
 2   health           52 non-null     int64
 3   defense          52 non-null     int64
 4   attack           52 non-null     int64
 5   attack_range     52 non-null     int64
 6   speed_of_attack  52 non-null     float64
 7   dps              52 non-null     int64
 8   skill_name       52 non-null     object
 9   skill_cost       52 non-null     object
 10  origin           52 non-null     object
 11  class            52 non-null     object
dtypes: float64(1), int64(6), object(5)
memory usage: 5.0+ KB

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      54 non-null     int64
 1   name    54 non-null     object
dtypes: int64(1), object(1)
memory usage: 996.0+ bytes

In [9]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79999 entries, 0 to 79998
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          79999 non-null  object
 1   gameDuration    79999 non-null  float64
 2   level           79999 non-null  int64
 3   lastRound       79999 non-null  int64
 4   Ranked          79999 non-null  int64
 5   ingameDuration  79999 non-null  float64
 6   combination     79999 non-null  object
 7   champion        79999 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB

In [10]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          80000 non-null  object
 1   gameDuration    80000 non-null  float64
 2   level           80000 non-null  int64
 3   lastRound       80000 non-null  int64
 4   Ranked          80000 non-null  int64
 5   ingameDuration  80000 non-null  float64
 6   combination     80000 non-null  object
 7   champion        80000 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB

In [11]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79999 entries, 0 to 79998
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          79999 non-null  object
 1   gameDuration    79999 non-null  float64
 2   level           79999 non-null  int64
 3   lastRound       79999 non-null  int64
 4   Ranked          79999 non-null  int64
 5   ingameDuration  79999 non-null  float64
 6   combination     79999 non-null  object
 7   champion        79999 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB

In [12]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          80000 non-null  object
 1   gameDuration    80000 non-null  float64
 2   level           80000 non-null  int64
 3   lastRound       80000 non-null  int64
 4   Ranked          80000 non-null  int64
 5   ingameDuration  80000 non-null  float64
 6   combination     80000 non-null  object
 7   champion        80000 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB

In [13]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          80000 non-null  object
 1   gameDuration    80000 non-null  float64
 2   level           80000 non-null  int64
 3   lastRound       80000 non-null  int64
 4   Ranked          80000 non-null  int64
 5   ingameDuration  80000 non-null  float64
 6   combination     80000 non-null  object
 7   champion        80000 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB

In [ ]:
# 티어 정보 통합

In [14]:
df3['source'] = 'Challenger'
df4['source'] = 'Diamond'
df5['source'] = 'Master'
df6['source'] = 'GrandMaster'
df7['source'] = 'Platinum'
df_total = pd.concat([df3, df4, df5, df6, df7], ignore_index=True)

In [15]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399998 entries, 0 to 399997
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   gameId          399998 non-null  object
 1   gameDuration    399998 non-null  float64
 2   level           399998 non-null  int64
 3   lastRound       399998 non-null  int64
 4   Ranked          399998 non-null  int64
 5   ingameDuration  399998 non-null  float64
 6   combination     399998 non-null  object
 7   champion        399998 non-null  object
 8   source          399998 non-null  object
dtypes: float64(2), int64(3), object(4)
memory usage: 27.5+ MB

In [ ]:
# 각 테이블의 행과 열 개수 확인하기

In [16]:
df1.shape, df2.shape, df_total.shape

((52, 12), (54, 2), (399998, 9))

In [ ]:
# 테이블 결측치 확인

In [17]:
df1.isna().sum()

name               0
cost               0
health             0
defense            0
attack             0
attack_range       0
speed_of_attack    0
dps                0
skill_name         0
skill_cost         0
origin             0
class              0
dtype: int64

In [18]:
df2.isna().sum()

id      0
name    0
dtype: int64

In [19]:
df_total.isna().sum()

gameId            0
gameDuration      0
level             0
lastRound         0
Ranked            0
ingameDuration    0
combination       0
champion          0
source            0
dtype: int64

In [20]:
df1.head()

,name,cost,health,defense,attack,attack_range,speed_of_attack,dps,skill_name,skill_cost,origin,class
0,gangplank,5,1000,30,60,1,1.00,60,gangplank_orbitalstrike,100/175,Space Pirate,"['Mercenary', 'Demolitionist']"
1,graves,1,650,35,55,1,0.55,30,graves_smokegrenade,50/80,Space Pirate,['Blaster']
2,neeko,3,800,35,50,2,0.65,33,neeko_popblossom,75/150,Star Guardian,['Protector']
3,darius,2,750,35,60,1,0.65,39,darius_spacepirateguillotine,0/60,Space Pirate,['Mana-Reaver']
4,rakan,2,600,35,45,2,0.70,32,rakan_grandentrance,50/100,Celestial,['Protector']

In [22]:
df_filtered = df1[(df1['cost'] >= 1) & (df1['cost'] <= 5)]

In [23]:
print("필터링 후 cost 컬럼의 고유 값:", df_filtered['cost'].unique())

필터링 후 cost 컬럼의 고유 값: [5 1 3 2 4]

In [31]:
df1['cost'].unique()

array([5, 1, 3, 2, 4])

In [24]:
df1['origin'].unique()

array(['Space Pirate', 'Star Guardian', 'Celestial', 'Dark Star',
       'Mech-Pilot', 'Cybernetic', 'Rebel', 'Valkyrie', 'Void', 'Chrono'],
      dtype=object)

In [25]:
df1['class'].unique()

array(["['Mercenary', 'Demolitionist']", "['Blaster']", "['Protector']",
       "['Mana-Reaver']", "['Sorcerer']", "['Demolitionist']",
       "['Vanguard']", "['Mystic']", "['Blademaster']", "['Brawler']",
       "['Mercenary', 'Blaster']", "['Infiltrator']", "['Starship']",
       "['Sniper']", "['Infiltrato']", "['Mana-Reaver', 'Blademaster']"],
      dtype=object)

In [38]:
df1.shape

(52, 12)

In [26]:
df2.head()

   id                  name
0   1            B.F. Sword
1   2           Recurve Bow
2   3  Needlessly Large Rod
3   4   Tear of the Goddess
4   5            Chain Vest

In [27]:
df_total.head()

,gameId,gameDuration,level,lastRound,Ranked,ingameDuration,combination,champion,source
0,KR_4247538593,2142.470703,8,35,1,2134.272217,"{'DarkStar': 2, 'Protector': 4, 'Rebel': 1, 'S...","{'JarvanIV': {'items': [27], 'star': 3}, 'Sona...",Challenger
1,KR_4247538593,2142.470703,9,35,2,2134.272217,"{'Blaster': 2, 'Mercenary': 1, 'Rebel': 6, 'Se...","{'Malphite': {'items': [7], 'star': 2}, 'Yasuo...",Challenger
2,KR_4247538593,2142.470703,8,34,3,2073.459229,"{'Cybernetic': 1, 'DarkStar': 3, 'Demolitionis...","{'KaiSa': {'items': [99, 2, 23], 'star': 2}, '...",Challenger
3,KR_4247538593,2142.470703,8,33,4,1998.146729,"{'Blaster': 1, 'Cybernetic': 1, 'DarkStar': 1,...","{'KaiSa': {'items': [44, 37], 'star': 2}, 'Ann...",Challenger
4,KR_4247538593,2142.470703,9,33,5,1986.443237,"{'Blaster': 2, 'Demolitionist': 2, 'Mercenary'...","{'Ziggs': {'items': [], 'star': 1}, 'Yasuo': {...",Challenger

In [32]:
df_total['Ranked'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [35]:
df_total = df_total[df_total['Ranked'] != 0]

In [36]:
df_total['Ranked'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
df_total.shape

(399906, 9)