In [126]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [127]:
#### 데이터 불러오기

# 챔피언 정보
df1 = pd.read_csv("TFT_Champion_CurrentVersion.csv")
# 아이템 정보
df2 = pd.read_csv("TFT_Item_CurrentVersion.csv")
#게임 매치 데이터
df3 = pd.read_csv("TFT_Challenger_MatchData.csv")
df4 = pd.read_csv("TFT_Diamond_MatchData.csv")
df5 = pd.read_csv("TFT_Master_MatchData.csv")
df6 = pd.read_csv("TFT_GrandMaster_MatchData.csv")
df7 = pd.read_csv("TFT_Platinum_MatchData.csv")

In [128]:
# 데이터 정보 확인 : 컬럼명, 데이터 타입, 결측치
df1.info()
df2.info()
df3.info()
df4.info()
df5.info()
df6.info()
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             52 non-null     object
 1   cost             52 non-null     int64
 2   health           52 non-null     int64
 3   defense          52 non-null     int64
 4   attack           52 non-null     int64
 5   attack_range     52 non-null     int64
 6   speed_of_attack  52 non-null     float64
 7   dps              52 non-null     int64
 8   skill_name       52 non-null     object
 9   skill_cost       52 non-null     object
 10  origin           52 non-null     object
 11  class            52 non-null     object
dtypes: float64(1), int64(6), object(5)
memory usage: 5.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      54 non-null     int64
 1   name    54 non-null     object
dtypes: int64(1), object(1)
memory usage: 996.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79999 entries, 0 to 79998
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          79999 non-null  object
 1   gameDuration    79999 non-null  float64
 2   level           79999 non-null  int64
 3   lastRound       79999 non-null  int64
 4   Ranked          79999 non-null  int64
 5   ingameDuration  79999 non-null  float64
 6   combination     79999 non-null  object
 7   champion        79999 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          80000 non-null  object
 1   gameDuration    80000 non-null  float64
 2   level           80000 non-null  int64
 3   lastRound       80000 non-null  int64
 4   Ranked          80000 non-null  int64
 5   ingameDuration  80000 non-null  float64
 6   combination     80000 non-null  object
 7   champion        80000 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79999 entries, 0 to 79998
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          79999 non-null  object
 1   gameDuration    79999 non-null  float64
 2   level           79999 non-null  int64
 3   lastRound       79999 non-null  int64
 4   Ranked          79999 non-null  int64
 5   ingameDuration  79999 non-null  float64
 6   combination     79999 non-null  object
 7   champion        79999 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          80000 non-null  object
 1   gameDuration    80000 non-null  float64
 2   level           80000 non-null  int64
 3   lastRound       80000 non-null  int64
 4   Ranked          80000 non-null  int64
 5   ingameDuration  80000 non-null  float64
 6   combination     80000 non-null  object
 7   champion        80000 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gameId          80000 non-null  object
 1   gameDuration    80000 non-null  float64
 2   level           80000 non-null  int64
 3   lastRound       80000 non-null  int64
 4   Ranked          80000 non-null  int64
 5   ingameDuration  80000 non-null  float64
 6   combination     80000 non-null  object
 7   champion        80000 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 4.9+ MB

In [129]:
#게임 매치 데이터 결합 & 새컬럼 생성
df3['tier'] = 'Challenger'
df4['tier'] = 'Diamond'
df5['tier'] = 'Master'
df6['tier'] = 'GrandMaster'
df7['tier'] = 'Platinum'
df_total = pd.concat([df3, df4, df5, df6, df7], ignore_index=True)

In [130]:
# 결합 데이터 확인
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399998 entries, 0 to 399997
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   gameId          399998 non-null  object
 1   gameDuration    399998 non-null  float64
 2   level           399998 non-null  int64
 3   lastRound       399998 non-null  int64
 4   Ranked          399998 non-null  int64
 5   ingameDuration  399998 non-null  float64
 6   combination     399998 non-null  object
 7   champion        399998 non-null  object
 8   source          399998 non-null  object
dtypes: float64(2), int64(3), object(4)
memory usage: 27.5+ MB

In [131]:
# 결측치 확인
df1.isna().sum()
df2.isna().sum()
df_total.isna().sum()

gameId            0
gameDuration      0
level             0
lastRound         0
Ranked            0
ingameDuration    0
combination       0
champion          0
source            0
dtype: int64

In [132]:
# 사용할 테이블 행/열 개수
df1.shape, df2.shape, df_total.shape

((52, 12), (54, 2), (399998, 9))

In [133]:
# 챔피언 정보 값 확인
df1.head()

,name,cost,health,defense,attack,attack_range,speed_of_attack,dps,skill_name,skill_cost,origin,class
0,gangplank,5,1000,30,60,1,1.00,60,gangplank_orbitalstrike,100/175,Space Pirate,"['Mercenary', 'Demolitionist']"
1,graves,1,650,35,55,1,0.55,30,graves_smokegrenade,50/80,Space Pirate,['Blaster']
2,neeko,3,800,35,50,2,0.65,33,neeko_popblossom,75/150,Star Guardian,['Protector']
3,darius,2,750,35,60,1,0.65,39,darius_spacepirateguillotine,0/60,Space Pirate,['Mana-Reaver']
4,rakan,2,600,35,45,2,0.70,32,rakan_grandentrance,50/100,Celestial,['Protector']

In [134]:
# 고유값 확인
df1['cost'].unique()

array([5, 1, 3, 2, 4])

In [135]:
df1['origin'].unique()
df1['origin'].nunique()

10

In [136]:
df1['class'].unique()
df1['class'].nunique()

16

In [137]:
# 아이템 정보 값 확인
df2.head()

   id                  name
0   1            B.F. Sword
1   2           Recurve Bow
2   3  Needlessly Large Rod
3   4   Tear of the Goddess
4   5            Chain Vest

In [138]:
# 결합 데이터 값 확인
df_total.head()

,gameId,gameDuration,level,lastRound,Ranked,ingameDuration,combination,champion,source
0,KR_4247538593,2142.470703,8,35,1,2134.272217,"{'DarkStar': 2, 'Protector': 4, 'Rebel': 1, 'S...","{'JarvanIV': {'items': [27], 'star': 3}, 'Sona...",Challenger
1,KR_4247538593,2142.470703,9,35,2,2134.272217,"{'Blaster': 2, 'Mercenary': 1, 'Rebel': 6, 'Se...","{'Malphite': {'items': [7], 'star': 2}, 'Yasuo...",Challenger
2,KR_4247538593,2142.470703,8,34,3,2073.459229,"{'Cybernetic': 1, 'DarkStar': 3, 'Demolitionis...","{'KaiSa': {'items': [99, 2, 23], 'star': 2}, '...",Challenger
3,KR_4247538593,2142.470703,8,33,4,1998.146729,"{'Blaster': 1, 'Cybernetic': 1, 'DarkStar': 1,...","{'KaiSa': {'items': [44, 37], 'star': 2}, 'Ann...",Challenger
4,KR_4247538593,2142.470703,9,33,5,1986.443237,"{'Blaster': 2, 'Demolitionist': 2, 'Mercenary'...","{'Ziggs': {'items': [], 'star': 1}, 'Yasuo': {...",Challenger

In [139]:
df_total['Ranked'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [140]:
# 등수가 1~8 밖에 있는 경우
df_total = df_total[df_total['Ranked'] != 0]
df_total['Ranked'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [141]:
# 중복행 개수가 8이 아닌 값 불러오기, 8이 아닌 개수 구하기
game_counts = df_total['gameId'].value_counts()
counts = game_counts[game_counts != 8]
# 결과를 화면에 출력합니다.
print(counts)
print(len(counts))

gameId
KR_4365284161    16
KR_4361594426    16
KR_4313697214    16
KR_4347884427    16
KR_4393787119    16
KR_4387247645    16
KR_4361773461    16
KR_4387025966    16
KR_4362846604    16
KR_4344513862    16
KR_4381231118    16
KR_4358922415    16
KR_4320079059    16
KR_4263820118    16
KR_4378896137    16
KR_4388134708    16
KR_4364453473    16
KR_4398618214    16
KR_4357966612    16
KR_4335870255     7
KR_4318806255     7
KR_4327053826     6
KR_4327058667     6
KR_4236285365     1
KR_4231144753     1
KR_4323594767     1
KR_4231208133     1
KR_4336328756     1
KR_4229542485     1
KR_4303195386     1
KR_4295022760     1
Name: count, dtype: int64
31

In [142]:
# 1. 이상치(8명 미만 게임) 제거
df_total = df_total[df_total.groupby('gameId')['gameId'].transform('count') >= 8].copy()

# 2. 16개인 게임은 정확히 8개만 남기기
df_total = df_total.groupby('gameId').head(8).reset_index(drop=True)

# 결과 확인
print(len(df_total))
print(df_total['gameId'].nunique())
print(df_total['gameId'].value_counts().nunique() == 1)

399720
49965
True

In [143]:
# 게임 시간이 15분(900초) 미만 또는 60분(3600초) 초과인 비정상 게임 제거
df_total = df_total[(df_total['gameDuration'] >= 900) & (df_total['gameDuration'] <= 3600)]

print(len(df_total))

399496

In [145]:
# single quote(') → double quote(")로 바꿔서 json이 인식하게 만들기
import json
import re

def str_to_dict(s):
    if pd.isna(s):
        return {}
    s = str(s)
    s = re.sub(r"(\w+):", r'"\1":', s)    # 키에 따옴표 붙이기
    s = s.replace("'", '"')              # ' 를 " 로 바꾸기
    try:
        return json.loads(s)
    except:
        return {}

# 적용
df_total['champion_count'] = df_total['champion'].apply(str_to_dict)

# 딕셔너리의 '키 개수' (챔피언 종류 수)가 6개 이상인 행만 필터링
df_total = df_total[df_total['champion_count'].apply(len) >= 6].copy()

# 임시 컬럼 삭제
df_total.drop(columns='champion_count', inplace=True)

print(len(df_total))

394724

In [147]:
# 세트 3 시너지 제거
bad_traits = ['Avatar', 'Glacial', 'Wind', 'TemplateTrait', 'Desert', 'Mountain', 'Ocean', 
              'Summoner', 'Ranger', 'Metal', 'Druid', 'Alchemist', 'Inferno', 'Berserker', 
              'Soulbound', 'Crystal', 'Assassin', 'Warden', 'Woodland', 'Electric', 
              'Predator', 'Mage', 'Poison', 'Light', 'Shadow']

pattern = '|'.join(bad_traits)
df_total = df_total[~df_total['combination'].astype(str).str.contains(pattern, na=False)].copy()

print(len(df_total))

325862